### ISSUE TITLE
error when import torchsnooper

### ISSUE THREAD

**Issue by Joe-annie** [zasdfgbnm/TorchSnooper#23]
> import torchsnooper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yfdai/.local/lib/python3.5/site-packages/torchsnooper/__init__.py", line 87
    return f'ndarray<{x.shape}, {x.dtype.name}>'
                                               ^
SyntaxError: invalid syntax

python version is 3.5
install with pip 19.0.3

**Comment by alexmojaki** [comment]
I don't know what versions torchsnooper claims to support but f-strings are definitely 3.6+ only.

**Comment by zasdfgbnm** [comment]
Hi @Joe-annie, I released v0.7.1 to remove f-string in order to be compatible with older python versions. Could you please `pip install --upgrade TorchSnooper` and try again?

**Comment by Joe-annie** [comment]
> Hi @Joe-annie, I released v0.7.1 to remove f-string in order to be compatible with older python versions. Could you please `pip install --upgrade TorchSnooper` and try again?

Thanks, it works at my env
