### ISSUE TITLE
TorchSnooper in IPython/Jupyter?

### ISSUE THREAD

**Issue by sachit-menon** [zasdfgbnm/TorchSnooper#35]
Hi, thanks for this great tool. I was wondering if you had any advice for how to use it effectively with IPython/Jupyter Notebooks. I seem to get a lot of extraneous information other than the desired output about the Tensors I'm doing operations on. 

Snoop seems to get around this with cell magic https://pypi.org/project/snoop/#ipythonjupyter-integration - is there a way to leverage this for TorchSnooper? 

Happy to provide more details, looking forward to hearing back from you.

**Comment by sachit-menon** [comment]
A workaround that seems to work reasonably is following the directions for using TorchSnooper with snoop and using snoop's cell magic itself:
```
import torchsnooper
%load_ext snoop
```
(insert some code cells here)
```
%%snoop
(insert PyTorch code you want to inspect)
```

I'm wondering if this is the recommended way, or if there's a more direct way I'm missing without installing snoop? Either way, thank you very much.

**Comment by zasdfgbnm** [comment]
If you use snoop, you can use
```python
import torchsnooper
torchsnooper.register_snoop()
```
and use the recommended approach of snoop https://github.com/alexmojaki/snoop#ipythonjupyter-integration

**Comment by sachit-menon** [comment]
Thanks, good to know that's the recommended approach.
