### ISSUE TITLE
Colorful words in terminal

### ISSUE THREAD

**Issue by TouKaienn** [zasdfgbnm/TorchSnooper#39]
Hello there! This is great work. I have a question that may not be directly related to TorchSnooper. While going through your readme, I noticed that the terminal output in the screenshot had colorful words. However, when I use this library in Win11 PowerShell, I do not receive the same colorful output (what I got is a similar output but is black and white). Is there anything I need to do to my terminal or any parameters I need to add to enable the colorful output?

**Comment by zasdfgbnm** [comment]
I think this question is better asked at [snoop](https://github.com/alexmojaki/snoop) or [PySnooper](https://github.com/cool-RR/PySnooper). I have no idea about color settings on PowerShell.

**Comment by TouKaienn** [comment]
Got it, thanks!
