### ISSUE TITLE
Running error in  Windows environment

### ISSUE THREAD

**Issue by InstantWindy** [zasdfgbnm/TorchSnooper#6]
When I run code , it shows "ContextualVersionConflict: (PySnooper 0.0.33 (f:\anaconda3.5.0\lib\site-packages), Requirement.parse('pysnooper>=0.1.0'), {'torchsnooper'})" .How to solve it ? Thanks!

**Comment by zasdfgbnm** [comment]
Hi @InstantWindy, it looks like you are having an old version of `PySnooper`, could you please try `pip install --upgrade PySnooper`?

**Comment by InstantWindy** [comment]
Yeah, It works, but when I install it offiline under linux environment, it shows "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-93uykazg/setup.py',   ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-93uykazg/" . Thanks!

**Comment by zasdfgbnm** [comment]
@InstantWindy What is the command you use to install it?

**Comment by InstantWindy** [comment]
pip install TorchSnooper-0.2.linux-x86_64.tar.gz

**Comment by zasdfgbnm** [comment]
@InstantWindy Did you download the tar.gz from github release page? The version number of TorchSnooper is currently determined dynamically and you need the `.git` directory as well in order to determine the version. Please git clone, don't download.

**Comment by InstantWindy** [comment]
I use the command "pip install TorchSnooper-0.2-py3-none-any.whl "

**Comment by zasdfgbnm** [comment]
Do you still have trouble using `pip install TorchSnooper-0.2-py3-none-any.whl `? this command success on my computer.

**Comment by InstantWindy** [comment]
Yes, it shows error as follows :
![F4@{01J0SPNL7)1SLSB46LS](https://user-images.githubusercontent.com/23608180/59811347-0c962c80-933c-11e9-935d-46514a631adf.png)

**Comment by zasdfgbnm** [comment]
Because you are offline, pip is unable to automatically install dependency `pysnooper` for you. You should download it manually at https://pypi.org/project/PySnooper/ and install it before installing torchsnooper.

**Comment by InstantWindy** [comment]
Yeah， Thanks, it works!
